services:
  postgis:
    image: postgis/postgis:15-3.4
    container_name: ecoruta-postgis
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    networks:
      - ecoruta_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: ecoruta-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgis
    networks:
      - ecoruta_net

  rutas-service:
    build: ./rutas-service
    container_name: rutas-service
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - postgis
    environment:
      DB_HOST: ecoruta-postgis
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    networks:
      - ecoruta_net

  backend:
    build: .
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - rutas-service
      - postgis
    env_file:
      - ./.env
    networks:
      - ecoruta_net

networks:
  ecoruta_net:

volumes:
  postgis_data:
  pgadmin-data:
